# Generated by Django 5.1.4 on 2025-04-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Age',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the age in years, if known.', null=True, verbose_name='Age (Optional)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Other')], default='male', max_length=10),
        ),
    ]
